### ISSUE TITLE
Π2019053 / Παραδοτέο 10 προσθήκη μελέτη περίπτωσης Github και βιογραφία Aaron Swartz

### ISSUE THREAD

**Issue by AimiliosPavlidis2001** [OompaLoompas/site#19]
Για [5ο παραδοτέο](https://github.com/OompaLoompas/site/issues/4) επέλεξα ως θέματα τη [Markdown](https://pibook-aimiliospavlidis2001.netlify.app/gallery/markdown/) και το [gedit](https://pibook-aimiliospavlidis2001.netlify.app/gallery/gedit/), για δέκατο παραδοτέο επέλεξα να ασχοληθώ με θέματα σχετικά με τη Markdown. Για αυτό τον λόγο υλοποίησα για μελέτη περίπτωσης το **Github** το οποίο όπως είναι γνωστό χρησιμοποιεί τη mark up language Markdown και για βιογραφία τον δημιουργό της Markdown τον **Aaron Swartz**.

[Netlify link για Github](https://pibook-aimiliospavlidis2001.netlify.app/case-study/github/)
[Netlify link για Aaron Swartz](https://pibook-aimiliospavlidis2001.netlify.app/biography/aaron-swartz/)

Θα εκτιμούσα πολύ ο @u2nmd και ο @p19pasc να αξιολογήσουν την συνεισφορά μου.

**Comment by u2nmd** [comment]
Πολύ καλές οι ιδέες σου, σχετίζονται άμεσα με την δουλειά σου στο 5ο παραδοτέο και τις κρίνω χρήσιμες και σημαντικές προσθήκες στο βιβλίο!

**Comment by p19pasc** [comment]
Συμφωνώ με τον u2nmd, επομένως θεωρώ μπορείς να προχωρήσεις στο Pull Request
