### ISSUE TITLE
Π2019034 - Προσθήκη των Manjaro Linux & Scikit-Learn

### ISSUE THREAD

**Issue by u2nmd** [OompaLoompas/site#2]
Στο site θα κάνω τις εξής προσθήκες:

* Tο **Manjaro Linux** σε ένα δικό μου σετ διαφανειών "Λειτουργικά Συστήματα" και στο χρονολόγιο "Λειτουργικά Συστήματα και Εφαρμογές".

* Την βιβλιοθήκη της python **Scikit-Learn** στο σετ διαφανειών "Εργαλεία και Τεχνικές" και στο χρονολόγιο "Γλώσσες Προγραμματισμού".

**Comment by AimiliosPavlidis2001** [comment]
@u2nmd μια χαρα ακουγεται απλά βάλε στα tags στο Scikit-Learn το tag library (στο _gallery αρχείο σου). Το λέω επειδη θες να το βάλεις στο χρονολόγιο "γλώσσες προγραματισμού" και επειδή δεν είναι γλώσσα προγραμματισμού ακριβώς , να φαίνεται από το tag.
@p19pasc συμφωνείς;

**Comment by p19pasc** [comment]
Δεν είμαι απόλυτα σίγουρος, αλλά πιστεύω ναι, με την άποψη ότι ως εργαλεία σε εκείνο το σετ διαφανειών αναφέρονται κάποιες εφαρμογές όπως θα ήταν το paint για ζωγραφική, το visual studio για ανάπτυξη κώδικα. Αλλά καλύτερα να ρωτήσουμε σε meeting.

**Comment by u2nmd** [comment]
> @u2nmd μια χαρα ακουγεται απλά βάλε στα tags στο Scikit-Learn το tag library (στο _gallery αρχείο σου). Το λέω επειδη θες να το βάλεις στο χρονολόγιο "γλώσσες προγραματισμού" και επειδή δεν είναι γλώσσα προγραμματισμού ακριβώς , να φαίνεται από το tag. @p19pasc συμφωνείς;

Έγινε Αιμίλιε το πρόσθεσα το tag
