### ISSUE TITLE
Π2019034 - Παραδοτέο 10: Προσθήκη case study Linux και biography Linus Torvalds

### ISSUE THREAD

**Issue by u2nmd** [OompaLoompas/site#20]
Για το [5ο παραδοτέο](https://github.com/OompaLoompas/site/issues/2) είχα επιλέξει να προσθέσω την διανομή linux Manjaro και την βιβλιοθήκη της python Scikit-Learn. 

Για το 10ο παραδοτέο αποφάσισα να προσθέσω κάτι που να σχετίζεται άμεσα με το Manjaro Linux. Έτσι σκέφτηκα να προσθέσω σαν case study το λειτουργικό σύστημα Linux στο οποίο βασίζεται το Manjaro και για biography τον δημιουργό του Linux τον Linus Torvalds.

* [Biography demo site](https://u2nmd-site.netlify.app/biography/linus-torvalds/)
* [Case Study demo site](https://u2nmd-site.netlify.app/case-study/linux/) 

Θα ήθελα την γνώμη σας @AimiliosPavlidis2001 @p19pasc

**Comment by p19pasc** [comment]
Προσωπικά πιστεύω είσαι εντάξει, αναμένω για το demo σου.
