### ISSUE TITLE
Π2019014 / ΠΑΡΑΔΟΤΕΟ 10

### ISSUE THREAD

**Issue by vasiliskampani** [OompaLoompas/site#21]
Στο [5ο παραδοτέο](https://github.com/OompaLoompas/site/issues/9/) είχα ασχοληθεί με το λειτουργικό σύστημα Fedora Linux και το βιντεοπαιχνίδι EverQuest και σε αυτό το παραδοτέο όντας η συνέχεια του 5ου αποφάσισα να υλοποιήσω τα εξής:

*  Προσθήκη του συστήματος διαχείρισης δυαδικών πακέτων **RPM package manager** ως μελέτη περίπτωσης, το όποιο χρησιμοποίει η Fedora 

* Προσθήκη του Μεξικανού προγραμματιστή **Miguel de lcaza** ο όποιος πέραν απο πολλα έργα συνεισφοράς του στο λογισμικό δημιούργησε και το γνώστο περιβάλλον επιφάνειας εργασίας ***GNOME*** το όποιο χρησιμοποιέιται πλέον απο παρα πολλα Linux distros συμπεριλαμβανομένου του Fedora, Debian.

1. [Demo link για την μελέτη περίπτωσής μου](https://vasiliskampani-rpm-miguel-de-lcaza.netlify.app//case-study/rpm/)
2. [Demo link για την βιογραφία](https://vasiliskampani-rpm-miguel-de-lcaza.netlify.app//biography/miguel-de-lcaza/)

Θα ήθελα απο τους @p19pasc και @AimiliosPavlidis2001 να αξιολογήσουν την συνεισφόρα μου

**Comment by p19pasc** [comment]
Ωραίες οι προσθήκες σου, αναμένουμε και την άποψη του @AimiliosPavlidis2001

**Comment by AimiliosPavlidis2001** [comment]
Βασίλη έχεις και από εμένα έγκριση.
