### ISSUE TITLE
Π2019110/ Παραδοτέο 5 (Βελτειωμένο): Προσθήκη Alpine Linux και OpenRc

### ISSUE THREAD

**Issue by p19pasc** [OompaLoompas/site#22]
Οι βελτειωμένες προσθήκες μου για το συμμετοχικό περιεχόμενο Α1+Α2, ύστερα από συνεννόηση με τον καθηγητή σε meeting:

* Alpine Linux,  σε ένα νέο σετ διαφανειών που δημιούργησα στο /_slides/operating-systems.md και στο _timeline/os-apps.md [Demo](https://p19pasc-site-alpine-openrc.netlify.app/gallery/alpine-linux/)
* OpenRc, σε νέο σετ διαφανειών που δημιούργησα στο /_slides/init-systems.md και σε νέο σετ χρονολογίου _timeline/init-systems.md [Demo](https://p19pasc-site-alpine-openrc.netlify.app/gallery/openrc/)

* [Παλιές προθήκες](https://github.com/OompaLoompas/site/issues/3)

@u2nmd @AimiliosPavlidis2001 @vasiliskampani

**Comment by AimiliosPavlidis2001** [comment]
και από εμένα εντάξει. Μπορώ να πω πως τα θέματά σου είναι πολύ κοντά στο θεματικό κέντρο του μαθήματος.

**Comment by u2nmd** [comment]
Και οι δύο προσθήκες σου πολύ ωραίες, ειδικά το Alpine Linux που το χρησιμοποιώ κιόλας στις ασκήσεις γραμμής εντολών. Έχεις την έγκρισή μου!
