### ISSUE TITLE
Π2019110/ Παραδοτέο 10 προσθήκη BusyBox(cs) και Louis Pouzin(bio)

### ISSUE THREAD

**Issue by p19pasc** [OompaLoompas/site#23]
Σύμφωνα με την βετλείωση μου στο [5ο περαδοτέο](https://github.com/OompaLoompas/site/issues/22) έκανα τις εξής προσθήκες για το Παραδοτέο 10:
* Προσθήκη του BussyBox(case study) ενός δυαδικού αρχείου που περιλαμβάνει εργαλεία και λειτουργίες όπως ένα λειτουργικό σύστημα πχ. UNIX. [Demo](https://p19pasc-b-meros.netlify.app/case-study/busybox/)
* Προσθήκη του Louis Pouzin(biography) ο οποίος, υιοθέτησε για πρώτη φορά τον όρο του shell, το οποίο υπάρχει στα λειτουργικά συστήματα και σχετίζεται με το OpenRc. [Demo](https://p19pasc-b-meros.netlify.app/biography/louis-pouzin/)

@u2nmd @AimiliosPavlidis2001 @vasiliskampani

**Comment by AimiliosPavlidis2001** [comment]
Οκέυ και από τα θέματα είναι αρκετά διαφορετικά αλλά θεωρώ πως με σωστή αιτιολόγηση καλύπτουν τις προδιαγραφές του μαθήματος. Οπότε έχεις οκέυ από εμένα.

**Comment by u2nmd** [comment]
Θα συμφωνήσω με τον @AimiliosPavlidis2001 αλλά εφόσον καταφέρεις και τα προσαρμόσεις έτσι ώστε να ταιριάζουν στα ζητούμενα του μαθήματος πιστεύω θα είσαι σε πολύ καλή θέση.
