### ISSUE TITLE
Π2019014 / ΠΑΡΑΔΟΤΕΟ 5 (Βελτιωμένο)

### ISSUE THREAD

**Issue by vasiliskampani** [OompaLoompas/site#28]
Στο [5ο παραδοτέο](https://github.com/OompaLoompas/site/issues/9/) είχα προσθέσει το λειτουργικό σύστημα Fedora Linux και το βιντεοπαιχνίδι EverQuest παρ'ολ'αυτά κατόπιν συζητήσεων του καθηγητή με άλλους συμφοιτητές μου φάνηκε πως τα βιντεοπαιχνίδια δεν έχουν άμεση σχέση με το μάθημα που διδάσκεται γιαυτο αποφάσισα να κάνω ένα βελτιωμένο παραδότεο και να αλλάξω το δεύτερο θέμα μου με το βιντεοπαιχνιδι διατηρώντας το Fedora. Οπότε υλοποιήσα τα εξής 

* **Fedora Linux** (ελάχιστα βελτιωμένο caption απο το προηγούμενο). Δημιούργησα νεο slide operating-systems.md και το πρόσθεσα στο timeline os-apps.md

* **Linux Kernel** τον μονολιθικό πυρήνα που αποτελεί τμήμα λειτουργικου συστήματος και τον μεσολαβητή (hardware/software) που χρησιμοποιείται για τα Linux λειτουργικά συστήματα. Δημιούργησα neo slide kernel.md και νεο timeline kernel.md και το πρόσθεσα.

Το [demo](https://vasiliskampani-fedora-kernel.netlify.app/gallery/fedora-linux/) μου για το  Fedora Linux
To [demo](https://vasiliskampani-fedora-kernel.netlify.app/gallery/linux-kernel/) μου για το Linux kernel

**Comment by AimiliosPavlidis2001** [comment]
μια χαρά από εμένα και συνδέεται πολύ περισσότερο με το θέμα του μαθήματος.

**Comment by p19pasc** [comment]
Οκ και από εμένα. Μπορείς να προχωρήσεις στα pull requests

**Comment by u2nmd** [comment]
Οι προσθήκες σου είναι εύστοχες, επομένως το επόμενο βήμα για εσένα είναι τα αντίστοιχα pull requests.
